### ISSUE TITLE
支持 Linux ARM/ARM64

### ISSUE THREAD

**Issue by yoooogaQAQ** [cssxsh/mirai-selenium-plugin#16]
在树莓派上运行，插件下载的浏览器和驱动都提示
`cannot execute binary file: Exec format error`
希望能支持 Linux ARM/ARM64

**Comment by cssxsh** [comment]
浏览器 和 浏览器驱动貌似都没有对 arm 的 官方支持，回头再看看

**Comment by cssxsh** [comment]
没有找到直接的 arm64 版 官方下载支持

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/mirai-selenium-plugin/releases/tag/v2.2.1-M1

由于没有比较好的直接对应版本驱动的方式，现在 arm64 系统需要通过指定下列对应 JVM 属性 来手动配置 driver 程序

Chrome/Chromium : `webdriver.chrome.driver`
Firefox: `webdriver.gecko.driver`

aarch64 的驱动有些系统应该是可以通过 包管理 直接安装 浏览器驱动的 https://pkgs.org/search/?q=chromedriver

`-Dwebdriver.chrome.driver=/usr/bin/chromedriver`

**Comment by cssxsh** [comment]
@mxsix112
