### ISSUE TITLE
浏览器没有关闭

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/mirai-selenium-plugin#7]
不知道是不是`bilibili-helper`的问题
不过看`GeckoMain`没有被清理
最近内存一直缓慢升高，甚至有几次死机

![image](https://user-images.githubusercontent.com/93422095/148051505-7a73c7fe-5d19-4527-bdc4-8ee5d6c11ada.png)

**Comment by cssxsh** [comment]
关闭 `bilibili-helper` (`mcl`) 之后 内存会下降吗

**Comment by LaoLittle** [comment]
> 关闭 `bilibili-helper` (`mcl`) 之后 内存会下降吗

关闭 bili-helper 后，即使没有关闭selenium，内存占用也下降了

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/mirai-selenium-plugin/releases/tag/v2.0.2

尝试通过 DriverCache 定期 destroy

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/mirai-selenium-plugin/releases/tag/v2.0.4

优化 destroy

**Comment by LaoLittle** [comment]
已解决
